export const GET_PASSENGER_REQUEST = "GET_PASSENGER_REQUEST";
export const GET_PASSENGER_SUCCESS = "GET_PASSENGER_SUCCESS";
export const GET_PASSENGER_FAILURE = "GET_PASSENGER_FAILURE";

export const GET_FOREIGN_PASSENGER_REQUEST = "GET_FOREIGN_PASSENGER_REQUEST";
export const GET_FOREIGN_PASSENGER_SUCCESS = "GET_FOREIGN_PASSENGER_SUCCESS";
export const GET_FOREIGN_PASSENGER_FAILURE = "GET_FOREIGN_PASSENGER_FAILURE";

export const ADD_PASSENGER_AUTH_REQUEST = "ADD_PASSENGER_AUTH_REQUEST";
export const ADD_PASSENGER_AUTH_SUCCESS = "ADD_PASSENGER_AUTH_SUCCESS";
export const ADD_PASSENGER_AUTH_FAILURE = "ADD_PASSENGER_AUTH_FAILURE";

export const ADD_CREDIT_REQUEST = "ADD_CREDIT_REQUEST";
export const ADD_CREDIT_SUCCESS = "ADD_CREDIT_SUCCESS";
export const ADD_CREDIT_FAILUER = "ADD_CREDIT_FAILURE";

export const GET_CREDIT_REQUEST = "GET_CREDIT_REQUEST";
export const GET_CREDIT_SUCCESS = "GET_CREDIT_SUCCESS";
export const GET_CREDIT_FAILUER = "GET_CREDIT_FAILURE";

export const GEN_TOKEN_REQUEST = "GEN_TOKEN_REQUEST";
export const GEN_TOKEN_SUCCESS  = "GEN_TOKEN_SUCCESS";
export const GEN_TOKEN_FAILURE = "GEN_TOKEN_FAILURE";


export const GET_TOKEN_REQUEST = "GET_TOKEN_REQUEST";
export const GET_TOKEN_SUCCESS  = "GET_TOKEN_SUCCESS";
export const GET_TOKEN_FAILURE = "GET_TOKEN_FAILURE";

export const GET_TRAVEL_REQUEST = "GET_TRAVEL_REQUEST";
export const GET_TRAVEL_SUCCESS  = "GET_TRAVEL_SUCCESS";
export const GET_TRAVEL_FAILURE = "GET_TRAVEL_FAILURE";


export const ADD_TRAVEL_REQUEST = "ADD_TRAVEL_REQUEST";
export const ADD_TRAVEL_SUCCESS = "ADD_TRAVEL_SUCCESS";
export const ADD_TRAVEL_FAILURE = "ADD_TRAVEL_FAILURE";


